version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    ports:
      - "2181:2181"


  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    links: 
      - zookeeper
    environment:


      #KAFKA_ADVERTISED_HOST_NAME: kafka
      #KAFKA_ADVERTISED_PORT: "9092"
      #KAFKA_CREATE_TOPICS: "mytopic:1:1"
      #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #HOSTNAME_COMMAND: "echo 127.0.0.1"
      #KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      #KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      #KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE

      #KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka #127.0.0.1
      KAFKA_CREATE_TOPICS: "order:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  costumer:
    build:
      context: .
      dockerfile: Costumer/Dockerfile
    image: costumer:latest
    links: 
     - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: docker
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
  orders:
    build: 
      context: .
      dockerfile: Orders/Dockerfile
    image: orders:latest
    links: 
     - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: docker
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      #GROUP_ID: docker-group
      #AUTO_OFFSET_RESET: largest
